#!/bin/bash
UPDATELCD=/home/pi/chairbot/updatelcd

sudo sixad --stop &

if hcitool dev|grep hci0; then
  $UPDATELCD "Bluetooth OK"
else
  $UPDATELCD "No Bluetooth device"
  exit
fi

$UPDATELCD "Start sixad"
sudo sixad --start &
$UPDATELCD "Press PS button"

while true; do
  if dmesg |grep "Sony Computer"; then
    $UPDATELCD "Connected"
    break
  fi
done

if [ -e /home/pi/chairbot/noautostart ]; then
    $UPDATELCD "NO AUTOSTART"    
else
    $UPDATELCD "Start controller"
    /home/pi/chairbot/controller/controller > /dev/null &
fi
