#!/bin/bash
INETADDR=`ifconfig eth0 | grep "inet addr" | cut -d ' ' -f 12 | sed -e s/addr://`
LCDPORT=/dev/ttyUSB0
LCD="/home/pi/agalanin-smartie-utils-aaa87234f4eb/smartie-cat.tcl -tty $LCDPORT -height 2"
echo -e "$INETADDR\nStart sixad" | $LCD
sudo sixad --start &
echo -e "$INETADDR\nPress PS button" | $LCD

while true; do
  if dmesg |grep "Sony Computer"; then
    echo -e "$INETADDR\nConnected" | $LCD
    break
  fi
done

echo -e "$INETADDR\nStart controller" | $LCD
/home/pi/chairbot/controller/controller > /dev/null &
