#!/bin/bash
INETADDR=`ifconfig eth0 | grep "inet addr" | cut -d ' ' -f 12 | sed -e s/addr://`
LCDPORT=/dev/lcdsmartie
LCD="/home/pi/agalanin-smartie-utils-aaa87234f4eb/smartie-cat.tcl -tty $LCDPORT -height 2"
echo -e "$INETADDR\n$1" | $LCD
