#BOARD_TAG = lardu_328p
BOARD_TAG = nano
BOARD_SUB = atmega328old
#ARDMK_VENDOR = LGT
ARDMK_VENDOR = archlinux-arduino
AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SoftwareSerial Wire
CXXFLAGS_STD=-std=c++11
include /usr/share/arduino/Arduino.mk
